### PR TITLE
2 0 0

### PR DESCRIPTION
**Pull request by philschmid**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: e1b6317dfe849b53fa11694daa55323884892e2d
* Result: FAILED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=a0cc10de-6651-4cc5-825f-af4471a5e7eb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: 46c63480c4ce0a43cd665f274587f5b371717505
* Result: FAILED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=6733f031-c42e-45da-99aa-eb2558a3e822%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by haixiw** [comment]
we should update the release.json https://github.com/awslabs/llm-hosting-container/blob/main/releases.json#L40-L47 according with the device type.

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: 46c63480c4ce0a43cd665f274587f5b371717505
* Result: FAILED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=c5685bf9-8136-45f1-91ff-21fdaca7d80e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request closed without merging**
