### PR TITLE
Release Neuronx TGI 0.0.22

### PR DESCRIPTION
**Pull request by Captainia**
*Issue #, if available:*

*Description of changes:*

Taking over the PR from HF to add 0.0.22 NeuronX TGI and 2.0.2 TGI: https://github.com/awslabs/llm-hosting-container/pull/71

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: e37025d5a7f1a20928dfdf439132af529fed9b13
* Result: FAILED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=46e4d108-cdda-41dd-98b6-4bca992ed352%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: 3a03dc9848eccb23a5d623b3a17a5b72af9d807d
* Result: FAILED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1e4fac01-b38d-4090-b69a-89db57ad35ae%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: 4a5510c576db72086f3eafb9af80256893bc9ec1
* Result: FAILED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=051f9478-d488-4582-96d1-995b687273ce%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: dc17fc0c29d97d8d7dc7cd19edd995959c3b0930
* Result: FAILED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b946fedd-fe67-4d26-a725-4e4e6a2d974d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: 5f591ea88f4d8933cf32a9888e158ed4c5f3cbe3
* Result: FAILED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4c7bf6f1-3dc9-41c0-85b2-2002ad7c8c14%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: 96312fd4c42627dec5833410761d4a782e4f1fde
* Result: FAILED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=f1d9309b-3e24-4aa9-b6dd-9186e228c8bb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: 608426c5fe2e0a8bdca4f5c8ef68d13d2e56862c
* Result: SUCCEEDED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=bdf5d8ba-503d-454a-8e42-49fe233209fc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by amzn-choeric** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: tgi-pr-inf2
* Commit ID: 81e3fd29daf0e0615c3b10f04cda8864e3e7a740
* Result: SUCCEEDED
* [Build Logs](https://cua665myu4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=02f423b0-489f-4b32-b1a1-fd0789f60c82%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by haixiw — APPROVED** [review]

**Pull request merged**
