### PR TITLE
ADD TGI v1.0.2

### PR DESCRIPTION
**Pull request by philschmid**
# What does this PR do

This PR adds TGI 1.0.1, which includes several improvements and bug fixes compared to 0.9.3.

See: 
* [v0.9.4](https://github.com/huggingface/text-generation-inference/releases/tag/v0.9.4)
* [v1.0.1](https://github.com/huggingface/text-generation-inference/releases/tag/v1.0.1)

Features to highlight are:
* GPQ int4 inference for llama
* Exllama kernels for faster latency
* BNB int4 inference
* RoPE scaling for deployment, e.g. [Amazon/FalconLite](https://huggingface.co/amazon/FalconLite)

### CODE REVIEW

**Comment by philschmid** [comment]
Cannot add reviewer pinging here: @xyang16 @frankfliu @ashivadi

**Comment by xyang16** [comment]
@amzn-choeric

**Comment by weiZhenkun** [comment]
@amzn-choeric can you review this PR?

**Review by amzn-choeric — CHANGES_REQUESTED** [review]

**Comment by philschmid** [comment]
Updated to 1.0.2 with the fix for tokenizers

**Comment by philschmid** [comment]
Thank you for adding the `clean` and license @amzn-choeric

**Review by amzn-choeric — APPROVED** [review]
Noting that I am looking into slightly changing that one line for THIRD-PARTY-LICENSES, but that can be done as a follow-up PR.

**Pull request merged**
